import Auth from '@/containers/Auth/Auth';
import JobUpload from '@/containers/JobUplaod/JobUpload'
import Head from 'next/head'
import { useEffect } from 'react';
import { useSelector } from 'react-redux'
import { toast } from 'react-toastify';
import axios from 'axios';
import * as actions from '@/store/actions';
import { useDispatch } from 'react-redux';

export default function Home() {
  const user = useSelector(state => state.auth.user);
  const dispatch = useDispatch();

  useEffect(() => {
    if (user) {
      getOrganizations();
    }
  }, [user])

  const getOrganizations = async () => {
    try {
      const res = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/organization/all`);
      dispatch(actions.setCompanies(res.data));
    } catch (e) {
      toast.error("Something went wrong while fetching organizations");
      console.log(e);
    }
  }



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
      </Head>
      {
        user ? <JobUpload /> : <Auth />
      }
    </>
  )
}
